package kb

// Gate: a KB compile has actually been run for the source that changed.
//
// The graph checker asks whether the KB's edges RESOLVE. This asks whether
// anyone LOOKED at it. Those are different failures and only the second one
// produces a confidently-wrong article, which is worse than no article at all:
// an agent is instructed to read the KB first, so it acts on the stale text
// instead of reading the code.
//
// ## State is PER FILE, deliberately
//
// The manifest maps each KB-owned source path to a hash of its content at the
// last compile. Staleness is "this file's content differs from what was
// reviewed", which is the actual question.
//
// The design this replaced used a single `last_compiled_commit` stamp and
// diffed trees against it. That made every MERGE look like drift: bringing a
// trunk branch down into a feature branch changes the tree, so the branch owed
// a fresh compile for files someone had already reviewed on the other side.
// Three consecutive merge-downs produced three stamp-only "reviewed, already
// documented" commits — the check was measuring merges, not drift.
//
// Per-file hashes fix that by construction. Two branches compiling different
// files update disjoint entries and git merges them like any other file; two
// branches compiling the SAME file conflict, which is correct, because they
// both reviewed it and one of them is about to lose.
//
// ## The manifest is NOT regenerated by a hook, on purpose
//
// The reverse index is derived from the KB, so being stale means being wrong,
// and a hook may rewrite it freely. This manifest is the opposite: it records
// a JUDGEMENT ("these articles were checked against this content"). Regenerate
// it automatically and the check passes always and means nothing.
//
// ## What it cannot do
//
// It cannot tell whether the compile was any GOOD — only that one happened for
// this content. A `--write` with no reading is indistinguishable from a careful
// pass. That is why the compile skill prints what it checked.

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"os"
	"sort"
	"strings"
)

// The manifest is a FLAT, sorted, one-entry-per-line map of path -> sha256,
// with no header object. The shape is the design: two branches that compile
// different files touch disjoint lines and git merges them like any other
// file, while two that compile the SAME file conflict, correctly, because one
// of their reviews is about to lose. A metadata header would add lines that
// every branch shares and that a tool-version bump would conflict on, for no
// gain — what the file is belongs in this comment, which cannot conflict.

// ErrNoManifest reports an absent manifest.
//
// This is a FAILURE, never a skip. A missing manifest is indistinguishable
// from a deleted one, so skipping would make `rm .compiled-sources.json` a
// one-line bypass of the entire gate — the same shape as a test suite that
// passes because it found no tests. Its absence is not "nothing to check", it
// is "nothing is known". `kb compiled` is deliberately the only way to create
// one.
var ErrNoManifest = errors.New("manifest is missing")

// Stale is one file whose content has moved since it was last reviewed.
type Stale struct {
	Path     string
	Articles []string
	Reason   string // "changed", "new", or "unreviewed"
}

// Freshness compares the manifest against the current content of every
// KB-owned source file. ownership comes from the graph pass, so the two
// checkers cannot disagree about what the KB owns.
func Freshness(manifestPath string, ownership map[string][]string) ([]Stale, map[string]string, error) {
	recorded := map[string]string{}
	missing := false
	if data, err := os.ReadFile(manifestPath); err == nil {
		if err := json.Unmarshal(data, &recorded); err != nil {
			// A conflict here is EXPECTED, not exceptional: the per-file
			// design means two branches compiling the same file conflict on
			// purpose. So the error has to name the situation and, more
			// importantly, rule out the obvious fix. `kb compiled` would
			// resolve it by blanket-approving every file on both sides
			// unreviewed, which is precisely the review that was about to be
			// arbitrated.
			if bytes.Contains(data, []byte("<<<<<<<")) {
				return nil, nil, fmt.Errorf(
					"%s has unresolved merge conflict markers.\n\n"+
						"This is expected: two branches recorded a compile for "+
						"the same file, and one of those reviews is about to "+
						"lose. Resolve it by hand, keeping the hash from the "+
						"side whose review you trust.\n\n"+
						"Do NOT resolve it with `kb compiled`. That would "+
						"re-record every file on both sides as reviewed, "+
						"including the ones nobody looked at, which is the one "+
						"use that defeats this gate.", manifestPath)
			}
			return nil, nil, fmt.Errorf("%s is not valid JSON: %w", manifestPath, err)
		}
	} else if os.IsNotExist(err) {
		missing = true
	} else {
		return nil, nil, err
	}

	current := map[string]string{}
	var stale []Stale
	paths := make([]string, 0, len(ownership))
	for p := range ownership {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	for _, p := range paths {
		// Only files with an owning ARTICLE. A file the index lists for its
		// test links alone has nothing to re-read, so failing on it would
		// hand the agent a filename and no scope — which is the "go read the
		// KB" outcome this check exists to replace.
		if len(ownership[p]) == 0 {
			continue
		}
		data, err := os.ReadFile(p)
		if err != nil {
			// A file the KB owns that is no longer readable is the graph
			// checker's problem, not this one's. Skip rather than double-report.
			continue
		}
		sum := sha256.Sum256(data)
		h := hex.EncodeToString(sum[:])
		current[p] = h

		prev, seen := recorded[p]
		switch {
		case !seen:
			stale = append(stale, Stale{p, ownership[p], "new"})
		case prev != h:
			stale = append(stale, Stale{p, ownership[p], "changed"})
		}
	}
	if missing {
		return stale, current, ErrNoManifest
	}
	return stale, current, nil
}

// WriteManifest records a compile. Only ever called by an explicit `kb
// compiled`, never by a hook.
func WriteManifest(path string, sources map[string]string) error {
	raw, err := json.MarshalIndent(sources, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(path, append(raw, '\n'), 0o644)
}

// GroupByArticle renders stale files grouped by the article that owns them, so
// the re-read is SCOPED rather than "go read the KB". This grouping is the
// output the compile skill consumes as its work list; it is more precise than
// a commit range, because a file touched and reverted since the last compile
// does not appear at all.
func GroupByArticle(stale []Stale) string {
	byArticle := map[string][]string{}
	var unowned []string
	for _, s := range stale {
		if len(s.Articles) == 0 {
			unowned = append(unowned, s.Path)
			continue
		}
		for _, a := range s.Articles {
			byArticle[a] = append(byArticle[a], s.Path+"  ("+s.Reason+")")
		}
	}
	ids := make([]string, 0, len(byArticle))
	for a := range byArticle {
		ids = append(ids, a)
	}
	sort.Strings(ids)

	var b strings.Builder
	for _, a := range ids {
		files := byArticle[a]
		sort.Strings(files)
		fmt.Fprintf(&b, "  %s.md\n", a)
		for _, f := range files {
			fmt.Fprintf(&b, "    %s\n", f)
		}
	}
	if len(unowned) > 0 {
		sort.Strings(unowned)
		b.WriteString("  (no owning article — the graph checker's orphan ratchet covers these)\n")
		for _, f := range unowned {
			fmt.Fprintf(&b, "    %s\n", f)
		}
	}
	return b.String()
}
