package kb

import (
	"fmt"
	"os"
	"sort"
	"strings"
)

// A ratchet grandfathers what is already wrong, fails anything NEW, and
// requires an entry that stops being wrong to be removed by regenerating. So
// the list can only ever shrink.
//
// The load-bearing rule is that `--write` may SHRINK a baseline and never grow
// it. Otherwise regenerating after adding an undocumented file silently
// legitimises it, and the gate quietly stops gating. That is the difference
// between a ratchet and a todo list.

const orphanHeaderTmpl = `# Production source files with no %s home, as of the last --write.
#
# GENERATED by ` + "`kb graph --write`" + `. Do not hand-edit.
#
# This is a RATCHET, not a todo list. The check fails if a file NOT listed here
# becomes an orphan, and also fails if a file listed here stops being one
# without the baseline being regenerated. So the list can only shrink.
#
# To remove an entry: name the file in the ` + "`## FILES`" + ` block of the article that
# owns it (or widen that article's ` + "`covers:`" + ` glob), then re-run with --write.
`

const deadEndHeaderTmpl = "# KB articles with no outbound `## SEE ALSO` edge, as of the last --write.\n" +
	"#\n" +
	"# GENERATED by `kb graph --write`. Do not hand-edit.\n" +
	"#\n" +
	"# A RATCHET, like .orphans-baseline.txt: a NEW dead end fails the build, and an\n" +
	"# entry that gains an edge must be removed by regenerating. The list can only\n" +
	"# shrink.\n" +
	"#\n" +
	"# An article nothing points out of can only be left via INDEX.md — the star\n" +
	"# topology a typed graph exists to replace. A rule with no check decays: the\n" +
	"# repo this was extracted from went from 9 such articles to 14 while the rule\n" +
	"# was written down and unenforced.\n" +
	"#\n" +
	"# To remove an entry: add a `## SEE ALSO` link whose reason names a specific\n" +
	"# obligation or invariant in the target article, not a topic.\n"

// readBaseline returns the non-comment, non-blank entries of a baseline file.
func readBaseline(path string) (map[string]bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	out := map[string]bool{}
	for _, l := range strings.Split(string(data), "\n") {
		if t := strings.TrimSpace(l); t != "" && !strings.HasPrefix(l, "#") {
			out[t] = true
		}
	}
	return out, nil
}

// writeRatchet writes entries to path, refusing if that would GROW the list.
func (c *Checker) writeRatchet(path, header string, entries []string, noun, fix string) {
	if existing, err := readBaseline(path); err == nil {
		var added []string
		for _, e := range entries {
			if !existing[e] {
				added = append(added, e)
			}
		}
		if len(added) > 0 {
			shown := added
			ellipsis := ""
			if len(shown) > 5 {
				shown, ellipsis = shown[:5], "\n  …"
			}
			c.errf("refusing to write %s: it would GROW by %d %s, which would "+
				"widen the ratchet.\n  %s%s\n  %s",
				path, len(added), noun, strings.Join(shown, "\n  "), ellipsis, fix)
			return
		}
	}
	body := header
	if len(entries) > 0 {
		body += strings.Join(entries, "\n") + "\n"
	}
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		c.errf("writing %s: %v", path, err)
		return
	}
	fmt.Printf("kb graph: wrote %s (%d %s).\n", path, len(entries), noun)
}

// checkRatchet compares current state against the committed baseline.
func (c *Checker) checkRatchet(path string, current []string, onNew func(string), noun string) {
	baseline, err := readBaseline(path)
	if err != nil {
		c.errf("%s is missing. Run `kb graph --write` to create it.", path)
		return
	}
	cur := map[string]bool{}
	for _, e := range current {
		cur[e] = true
		if !baseline[e] {
			onNew(e)
		}
	}
	var fixed []string
	for e := range baseline {
		if !cur[e] {
			fixed = append(fixed, e)
		}
	}
	sort.Strings(fixed)
	if len(fixed) > 0 {
		shown := fixed
		ellipsis := ""
		if len(shown) > 3 {
			shown, ellipsis = shown[:3], ", …"
		}
		c.errf("%s lists %d %s that no longer qualify (%s%s). Run `kb graph "+
			"--write` to shrink the baseline. It is a ratchet: it may only "+
			"ever get smaller.", path, len(fixed), noun, strings.Join(shown, ", "), ellipsis)
	}
}

// CheckOrphanRatchet enforces that every production source file has a KB home.
func (c *Checker) CheckOrphanRatchet(ownership map[string][]string, write bool) {
	var orphans []string
	for _, f := range c.Tracked {
		if c.Cfg.IsProductionSource(f) && ownership[f] == nil {
			orphans = append(orphans, f)
		}
	}
	sort.Strings(orphans)

	path := c.Cfg.OrphanBaselinePath()
	if write {
		c.writeRatchet(path, fmt.Sprintf(orphanHeaderTmpl, c.Cfg.KBDir+"/"),
			orphans, "orphans",
			"Claim them instead — name each in the `## FILES` block of the "+
				"article that owns it, or widen that article's `covers:` glob.")
		return
	}
	c.checkRatchet(path, orphans, func(f string) {
		c.errf("%s has no KB home. Claim it — add it to an article's `## FILES` "+
			"block, or widen that article's `covers:` glob. (Every production "+
			"source file must be documented somewhere; this is the ratchet.)", f)
	}, "file(s)")
}

// CheckDeadEndRatchet enforces that articles point somewhere.
//
// Deliberately NOT checking edge QUALITY. The reason on an edge must name an
// obligation, not a topic ("related to scoring" is not an edge) — and no
// checker can tell those apart. This catches absence only; a reviewer catches
// emptiness.
func (c *Checker) CheckDeadEndRatchet(write bool) {
	var deadEnds []string
	for _, id := range c.sortedIDs() {
		if !c.Articles[id].HasOutboundEdge() {
			deadEnds = append(deadEnds, id)
		}
	}

	path := c.Cfg.DeadEndBaselinePath()
	if write {
		c.writeRatchet(path, deadEndHeaderTmpl, deadEnds, "dead ends",
			"Give each a `## SEE ALSO` edge naming a specific obligation in "+
				"the article it points at, not a topic.")
		return
	}
	var fresh []string
	c.checkRatchet(path, deadEnds, func(id string) {
		fresh = append(fresh, id)
	}, "article(s)")
	if len(fresh) > 0 {
		c.errf("%d article(s) have no outbound `## SEE ALSO` edge and are not "+
			"grandfathered: %s.\n"+
			"  An article nothing points OUT of is a dead end — a reader who "+
			"lands there can only return to INDEX.md, which is the star "+
			"topology the typed graph replaced.\n"+
			"  Add a `## SEE ALSO` entry naming a specific obligation or "+
			"invariant in the target (\"related to X\" is not an edge).",
			len(fresh), strings.Join(fresh, ", "))
	}
}
